{{ if .Values.cache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jasper.fullname" . }}-cache
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cache.service.type }}
  ports:
    - port: {{ .Values.cache.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jasper.cache.selectorLabels" . | nindent 4 }}
{{ end }}
