{{- if .Values.cache.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jasper.fullname" . }}-cache
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jasper.fullname" . }}-cache-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "jasper.cache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        affinity: cache
        {{- include "jasper.cache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jasper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cache
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: JASPER_HEAP
              value: {{ .Values.cache.heap }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.cache.profiles }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.postgresql.fullnameOverride }}:5432/{{ .Values.postgresql.auth.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.fullnameOverride }}
                  key: postgres-password
            - name: SPRING_REDIS_HOST
              value: {{ .Values.config.redis }}
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Values.config.redis }}
            - name: JASPER_CACHE_API
              value: http://{{ include "jasper.fullname" . }}-cache
            - name: JASPER_MIN_ROLE
              value: {{ .Values.cache.minRole }}
            - name: JASPER_DEFAULT_ROLE
              value: {{ .Values.cache.defaultRole }}
            - name: JASPER_ALLOW_USER_TAG_HEADER
              value: {{ .Values.cache.allowUserTagHeader | quote }}
            - name: JASPER_ALLOW_USER_ROLE_HEADER
              value: {{ .Values.cache.allowUserRoleHeader | quote }}
            - name: JASPER_ALLOW_AUTH_HEADERS
              value: {{ .Values.cache.allowAuthHeaders | quote }}
            - name: JASPER_SECURITY_CONTENT_SECURITY_POLICY
              value: {{ .Values.cache.csp | quote }}
            - name: JASPER_OVERRIDE_SECURITY_MODE
              value: {{ .Values.config.override.security.mode }}
            - name: JASPER_OVERRIDE_SECURITY_CLIENT_ID
              value: {{ .Values.config.override.security.clientId }}
            {{- if .Values.config.override.security.clientSecret }}
            - name: JASPER_OVERRIDE_SECURITY_BASE64_SECRET
              valueFrom:
                secretKeyRef:
                  name: jasper-jwt-config
                  key: override
            {{- end }}
            - name: JASPER_OVERRIDE_SECURITY_JWKS_URI
              value: {{ .Values.config.override.security.jwksUri }}
            - name: JASPER_OVERRIDE_SECURITY_USERNAME_CLAIM
              value: {{ .Values.config.override.security.usernameClaim }}
            - name: JASPER_OVERRIDE_SECURITY_TOKEN_ENDPOINT
              value: {{ .Values.config.override.security.tokenEndpoint }}
            - name: JASPER_OVERRIDE_SECURITY_MAX_REQUESTS
              value: {{ .Values.cache.maxRequestsOrigin | quote }}
            - name: JASPER_OVERRIDE_SERVER_MAX_REQUESTS
              value: {{ .Values.cache.maxRequests | quote }}
            - name: JASPER_OVERRIDE_SERVER_MAX_CONCURRENT_REQUESTS
              value: {{ .Values.cache.maxConcurrentRequests | quote }}
          livenessProbe:
            initialDelaySeconds: 120
            failureThreshold: 10
            timeoutSeconds: {{ .Values.cache.livenessTimeout }}
            httpGet:
              path: /management/health/liveness
              port: 8081
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /management/health/readiness
              port: 8081
          resources:
            {{- toYaml .Values.cache.resources | nindent 12 }}
      {{- with .Values.cache.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cache.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cache.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
    {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "jasper.fullname" .) }}
    {{- else }}
        - name: storage
      {{- if .Values.persistence.inMemory.enabled }}
          emptyDir:
            medium: Memory
        {{- if .Values.persistence.inMemory.sizeLimit }}
            sizeLimit: {{ .Values.persistence.inMemory.sizeLimit }}
        {{- end -}}
      {{- else }}
          emptyDir: {}
      {{- end -}}
    {{- end -}}
{{- end }}
