{{- if and (not .Values.postgresql.enabled) .Values.externalDatabase.password (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jasper.database.secretName" . }}
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "jasper.database.secretKey" . }}: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
