{{- if .Values.ingress.enabled -}}
{{- $fullName := include "jasper.fullname" . -}}
{{- range .Values.ingress.tenants -}}
{{- $tenant := default "default" (.origin | replace "@" "") -}}
{{- if .publicApi }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $tenant }}-pub
  labels:
    {{- include "jasper.labels" $ | nindent 4 }}
  annotations:
    {{- with .publicApiAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
      {{ .publicApiServerSnippet }}
      more_set_input_headers "Local-Origin: {{ .origin }}";
      more_set_input_headers "User-Tag: {{ .userTag }}";
      more_set_input_headers "User-Role: {{ .userRole }}";
      more_set_input_headers "Read-Access: {{ .readAccess }}";
      more_set_input_headers "Write-Access: {{ .writeAccess }}";
      more_set_input_headers "Tag-Read-Access: {{ .tagReadAccess }}";
      more_set_input_headers "Tag-Write-Access: {{ .tagWriteAccess }}";
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if .tlsSecretName }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .publicApiPath }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
---
{{- end }}
{{- end }}
{{- end }}
