apiVersion: v1
kind: Secret
metadata:
  name: jasper-jwt-config
type: Opaque
data:
{{- range .Values.config.tenants }}
{{- $tenant := default "default" .origin | replace "@" "" | upper }}
{{- if .clientSecret }}
  {{ $tenant }} }: {{ .clientSecret | b64enc | b64enc }}
{{- end }}
{{- end }}
