{{ if .Values.sshTunnel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jasper.fullname" . }}-ssh-tunnel
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sshTunnel.service.type }}
  ports:
    - port: {{ .Values.sshTunnel.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    affinity: ssh
    {{- include "jasper.selectorLabels" . | nindent 4 }}
{{ end }}
